name: pythonenv
channels:
  - defaults
  - conda-forge
dependencies:
  - annotated-types=0.6.0
  - antlr-python-runtime=4.9.3
  - anyio=4.6.2
  - black=24.8.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - certifi=2024.8.30
  - click=8.1.7
  - distro=1.9.0
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - hydra-core=1.3.2
  - idna=3.7
  - importlib_resources=6.4.0
  - jiter=0.6.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - llvm-openmp=14.0.6
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - omegaconf=2.3.0
  - openai=1.54.4
  - openblas=0.3.21
  - openblas-devel=0.3.21
  - openssl=3.0.15
  - packaging=24.1
  - pathspec=0.10.3
  - pip=24.2
  - platformdirs=3.10.0
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - python=3.11.10
  - pyyaml=6.0.2
  - readline=8.2
  - setuptools=75.1.0
  - sniffio=1.3.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - wandb=0.19.0
