# The following defines the task hyperparameters we used for training. 
# Validation sets have are iid, so the same ask hyperparameters.
# the how_many parameter for the composition task (last in the list) is varied in our experiments as specified in the paper.
data_module_name: SynthTasks
n_train_samples: 10000
n_val_samples: 4000
val_check_interval: null
seed: 325

# all values are inclusive. The lengths are not the number of tokens, but the length of the respective task

train_data_mix:
  - task: CopyTask
    logname: copy
    relative_many: 20000
    min_len: 10
    max_len: 40
  - task: CopyTask
    logname: revcpy
    reverse: true
    relative_many: 20000
    min_len: 10
    max_len: 40
  - task: PointerExecutionNeighbour
    logname: pe
    relative_many: 60000
    sub_task: seq
    min_len: 40
    max_len: 50
    min_hops: 10
    max_hops: 20
  - task: PointerExecutionNeighbour
    logname: pev
    relative_many: 100000
    sub_task: seqnext
    min_len: 30
    max_len: 40
    min_hops: 10
    max_hops: 15
  - task: PointerExecutionNeighbour
    logname: pen
    relative_many: 500000 # example number, varied in experiments to test compositional learning
    sub_task: next
    min_len: 40
    max_len: 50
    min_hops: 10
    max_hops: 20

val_data_mix:
  - task: CopyTask
    logname: copy
    relative_many: 1
    min_len: 10
    max_len: 40
  - task: CopyTask
    logname: revcpy
    reverse: true
    relative_many: 1
    min_len: 10
    max_len: 40
  - task: PointerExecutionNeighbour
    logname: pe
    relative_many: 1
    sub_task: seq
    min_len: 40
    max_len: 50
    min_hops: 10
    max_hops: 20
  - task: PointerExecutionNeighbour
    logname: pev
    relative_many: 1
    sub_task: seqnext
    min_len: 30
    max_len: 40
    min_hops: 10
    max_hops: 15
  - task: PointerExecutionNeighbour
    logname: pen
    relative_many: 1
    sub_task: next
    min_len: 40
    max_len: 50
    min_hops: 10
    max_hops: 20